AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
# create a function and API gateway to return hello world

#Input parameters - specify these at run-time
#Parameters:
#    someparameter:
#        Type: String

# global variable definitions
Globals:
  Function:
    Runtime: python2.7
    Timeout: 10

Resources:
  # helloworld function
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: aacorne-helloworld
      Description: aacorne-helloworld
      Handler: helloworld.lambda_handler
      Role: arn:aws:iam::282415712953:role/aacorne-lambdainvoke-role
      AutoPublishAlias: prod
      CodeUri: ./
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /
            Method: get
      Tags:
          Owner: aacorne
          Status: active
          Environment: development
          Name: aacorne-helloworld
      Tracing: Active

  # API Gateway setup, points to the helloworld Lambda
  APIGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: aacorne-helloworld
      StageName: prod
      DefinitionBody:
        swagger: 2.0
        info:
          title:
            Ref: AWS::StackName
        paths:
          "/":
            get:
              x-amazon-apigateway-integration:
                httpMethod: GET
                type: aws_proxy
                passthroughBehavior: when_no_match
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HelloWorldFunction.Alias}/invocations
              responses: {}
